version: "3.7"
services:
  backend:
    container_name: ona-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - ./skills:/opt/mycroft/skills
      - ./logs:/var/log/mycroft
      - ./backend:/opt/backend
      - venv:/opt/venv
      - catroton-cache:/tmp/catotron
    command: supervisord -c /opt/mycroft/supervisord.conf
  catotron:
    container_name: ona-catotron
    build:
      context: ./catotron-cpu
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    entrypoint: python server.py
volumes:
  venv:

