version: "3.7"
services:
  mycroft:
    container_name: mycroft
    build:
      context: .
    ports:
      - "8181:8181"
    environment:
      PULSE_SERVER: docker.for.mac.localhost
    volumes:
      - ./skills:/opt/mycroft/skills
      - ./docker-start.sh:/opt/mycroft/docker-start.sh
      - ../../vosk/model:/vosk/model
      - ./mycroft.conf:/root/.mycroft/mycroft.conf
      - ./logs:/var/log/mycroft
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    command: bash ./docker-start.sh

