apiVersion: v1
kind: Service
metadata:
  name: ona-catotron
spec:
  clusterIP: None
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: ona-catotron
  sessionAffinity: None
  type: ClusterIP