apiVersion: apps/v1
kind: Deployment
metadata:
  name: ona-backend
  labels:
    app: ona-backend
    tier: backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ona-backend
      tier: backend
  template:
    metadata:
      labels:
        app: ona-backend
        tier: backend
    spec:
      containers:
        - name: ona-backend
          image: assistent/ona-backend:0.0.2
          env:
            - name: VOSK_SERVER_HOST
              value: ona-vosk
            - name: CATOTRON_SERVER_HOST
              value: ona-catotron
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
          ports:
            - containerPort: 5678
              protocol: TCP
              name: http
