apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ona-backend-pvc-config
  labels:
    app: ona-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi