apiVersion: v1
kind: Service
metadata:
  name: ona-backend
spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: ona-backend
  sessionAffinity: ClientIP
  type: NodePort