apiVersion: apps/v1
kind: Deployment
metadata:
  name: ona-festival
  labels:
    app: ona-festival
    tier: backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ona-festival
      tier: backend
  template:
    metadata:
      labels:
        app: ona-festival
        tier: backend
    spec:
      containers:
        - name: ona-festival
          image: assistent/festival-tts:0.0.1
          ports:
            - containerPort: 8100
              protocol: TCP
              name: http
