apiVersion: apps/v1
kind: Deployment
metadata:
  name: ona-frontend
  labels:
    app: ona-frontend
    tier: frontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ona-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: ona-frontend
        tier: frontend
    spec:
      containers:
        - name: ona-frontend
          image: assistent/ona-frontend:0.0.3
          command: ["/app/start.sh"]
          env:
            - name: ONA_CONFIG_BACKEND_HOST
              value: "ona.assistent.cat"
            - name: ONA_CONFIG_BACKEND_PATH
              value: "ws/"
            - name: ONA_CONFIG_BACKEND_PORT
              value: "443"
            - name: ONA_CONFIG_USE_SSL
              value: "true"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
